# Path: docs/internal/pcode.spec.toml
#
# BẢN THIẾT KẾ TOOL (pcode) - PHIÊN BẢN 2
# (Dựa trên phản hồi: dùng argparse, output file mặc định)
# ---------------------------------
# python scripts/bootstrap_tool.py docs/internal/pcode.spec.toml
#

# --- 1. THÔNG TIN CƠ BẢN ---
[meta]
tool_name = "pcode"
script_file = "pack_code.py"
module_name = "pack_code"
logger_name = "pcode"

# --- 2. CẤU HÌNH CLI ---
[cli]
interface = "argparse"
allow_interspersed_args = true

[cli.help]
description = "Đóng gói nội dung của nhiều file/thư mục thành một file văn bản duy nhất."
epilog = "Ví dụ: pcode ./src -e 'py,md' -o context.txt"

# --- 3. DANH SÁCH ARGUMENTS (ARGPARSE) ---

# --- Input: Positional Argument ---
[[cli.args]]
name = "start_path"
type = "Path"
default = "."
help = "Đường dẫn (file hoặc thư mục) để bắt đầu quét."
is_argument = true

# --- Output: Tùy chọn file hoặc stdout ---
[[cli.args]]
name = "output"
short = "-o"
type = "Path"
# (Không có 'default'. Logic mặc định (tmp/) sẽ được xử lý trong script)
help = "File output để ghi. Mặc định: 'tmp/<input_name>.txt'"

[[cli.args]]
name = "stdout"
short = "-S"
type = "bool"
default = false
help = "In kết quả ra stdout (console) thay vì ghi file."

# --- Filter 1: Extensions ---
[[cli.args]]
name = "extensions"
short = "-e"
type = "str"
help = "Chỉ bao gồm các đuôi file này (vd: 'py,md'). Hỗ trợ +/-."

# --- Filter 2: Ignore ---
[[cli.args]]
name = "ignore"
short = "-I"
type = "str"
help = "Các pattern (giống .gitignore) để bỏ qua (THÊM vào config)."

# --- Filter 3: Gitignore Flag ---
[[cli.args]]
name = "no_gitignore"
short = "-N"
type = "bool"
default = false
help = "Không tôn trọng các file .gitignore."

# --- Mode 1: Dry Run ---
[[cli.args]]
name = "dry_run"
short = "-d"
type = "bool"
default = false
help = "Chỉ in danh sách file sẽ được đóng gói (không in nội dung)."

# --- Mode 2: No Header ---
[[cli.args]]
name = "no_header"
type = "bool"
default = false
help = "Không in header phân tách ('===== path/to/file.py =====')."

# --- Mode 3: No Tree (Đã đảo ngược logic) ---
[[cli.args]]
name = "no_tree"
type = "bool"
default = false
help = "Không in cây thư mục của các file được chọn ở đầu output."

# --- 4. TÀI LIỆU ---
[docs]
enabled = true
short_description = "Một công cụ để đóng gói (flatten) cây thư mục thành một file context.txt duy nhất."