# Path: docs/drafts/tool_spec.template.toml
# Template để tạo file <tên_tool>.spec.toml

# --- Phần [meta]: Thông tin cơ bản về tool ---
[meta]
# Tên tool (dùng cho file thực thi trong bin/, tên section config, v.v.)
tool_name = "new_tool"
# Tên file script Python trong thư mục scripts/
script_file = "new_tool.py"
# Tên thư mục module trong thư mục modules/
module_name = "new_tool"
# Tên logger (thường là tên tool viết hoa chữ cái đầu)
logger_name = "NewTool"

# --- Phần [cli]: Cấu hình giao diện dòng lệnh ---
[cli]
# Loại giao diện: "typer" (mặc định) hoặc "argparse"
interface = "argparse"
allow_interspersed_args = true


# Cấu hình trợ giúp (help text)
[cli.help]
# Mô tả ngắn gọn về tool (hiển thị với --help)
description = "Mô tả ngắn gọn về chức năng của new_tool."
# Văn bản hiển thị ở cuối phần trợ giúp (tùy chọn)
epilog = "Ví dụ sử dụng: new_tool --option value"

# Định nghĩa các đối số dòng lệnh [[cli.args]]
# Lặp lại khối này cho mỗi đối số
[[cli.args]]
# Tên đối số (dùng trong code Python và làm tên flag dài --name)
name = "input_path"
# (Tùy chọn) Tên flag ngắn (ví dụ: "-i")
short = "-i"
# Loại dữ liệu: "str", "int", "bool", "Path"
type = "Path"
# Văn bản trợ giúp cho đối số này
help = "Đường dẫn đến file hoặc thư mục đầu vào."
# (Tùy chọn) Giá trị mặc định. Nếu có, hằng số DEFAULT_INPUT_PATH sẽ được tạo.
# Đối với 'bool', default=true nghĩa là cờ sẽ tắt nó đi (store_false).
default = "."
# (Tùy chọn) Đặt thành true nếu đây là đối số vị trí (positional argument) thay vì tùy chọn (--flag).
# is_argument = true

# [[cli.args]]
# name = "verbose"
# short = "-v"
# type = "bool"
# help = "Bật chế độ hiển thị chi tiết."
# default = false

# [[cli.args]]
# name = "output_file"
# short = "-o"
# type = "str"
# help = "Đường dẫn file output (tùy chọn)."
# Mặc định None nếu không có 'default' cho option type 'str'/'int'/'Path'

# --- Phần [docs]: Cấu hình tạo tài liệu ---
[docs]
# Bật/tắt việc tạo file tài liệu Markdown ban đầu (true/false)
enabled = true
# Mô tả ngắn gọn sẽ được dùng trong file tài liệu
short_description = "Đây là công cụ mới tuyệt vời để làm việc X."