[tree]
show-submodules = false
use-gitignore = true
ignore = [
    ".git",
    ".venv",
    "__pycache__",
    "node_modules",
    "venv",
]
prune = [
    "build",
    "dist",
]
dirs-only = []

[cpath]
extensions = [
    "css",
    "js",
    "py",
    "py.template",
    "scss",
    "sh",
    "template.toml",
    "ts",
    "zsh",
]
ignore = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "out",
    "venv",
]

[sgen]
ignore = [
    "*.pyc",
    "*.pyo",
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "out",
    "venv",
]
restrict = [
    "modules",
    "utils",
]
dynamic_import_indicators = [
    "globals()[name]",
    "globals()[name] = obj",
    "import_module",
]
ast_module_list_name = "modules_to_export"
ast_all_list_name = "__all__"
