[tree]
show-submodules = false
use-gitignore = true
ignore = [
    ".git",
    "__pycache__",
    ".venv",
    "node_modules",
    "venv",
]
prune = [
    "build",
    "dist",
]
dirs-only = []

[cpath]
extensions = [
    "css",
    "js",
    "py",
    "scss",
    "sh",
    "template.toml",
    "ts",
    "zsh",
]
ignore = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "out",
    "venv",
]

[sgen]
ignore = [
    "*.pyc",
    "*.pyo",
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
    "node_modules",
    "out",
    "venv",
]
restrict = [
    "modules",
    "utils",
]
dynamic_import_indicators = [
    "globals()[name]",
    "globals()[name] = obj",
    "import_module",
]
ast_module_list_name = "modules_to_export"
ast_all_list_name = "__all__"

[pcode]
output_dir = "~/Documents/code.context"
extensions = [
    "bash",
    "cfg",
    "cfg.py",
    "ini",
    "json",
    "md",
    "py",
    "sh",
    "txt",
    "xml",
    "yaml",
    "yml",
    "zsh",
]
ignore = [
    ".DS_Store",
    ".git",
    ".hg",
    ".svn",
    ".venv",
    "__pycache__",
    "venv"
]
