# Path: pyproject.toml

[tool.black]
# Cài đặt Black tiêu chuẩn để thống nhất
line-length = 88
# Sử dụng cùng phiên bản target với pyright để nhất quán 
target-version = ['py314'] 
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.svn
  | \.DS_Store
  | \.venv
  | __pycache__
  | build
  | dist
  | node_modules
  | venv
  | out
)/
'''

# ---------------------------------------------------------------------------
# Cấu hình Pyright (Được di chuyển từ pyrightconfig.json)
# ---------------------------------------------------------------------------
[tool.pyright]
# Cấu hình môi trường thực thi 
executionEnvironments = [
  { root = ".", pythonVersion = "3.14", extraPaths = ["modules", "utils", "scripts"] }
]

# Chế độ kiểm tra type cơ bản
typeCheckingMode = "basic"

# Tắt các báo cáo lỗi/cảnh báo cụ thể
reportUnknownArgumentType = "none"
reportUnknownMemberType = "none"
reportUnusedImport = "none"
reportUnsupportedDunderAll = "none"
reportPossiblyUnboundVariable = "none"
reportUnknownVariableType = "none"
reportInvalidTypeForm = "none"
reportArgumentType = "none"

# Chỉ định các thư mục cần bao gồm và loại trừ
include = ["utils", "modules", "scripts"]
exclude = [ 
  "**/__pycache__",
  "**/.venv",
  "**/venv",
  "**/node_modules",
  "/scripts/internal/bootstrap_templates/*"
]