# Path: modules/check_path/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for check_path"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

COMMENT_RULES: Any
COMMENT_RULES_BY_EXT: Any
CONFIG_FILENAME: Any
CONFIG_SECTION_NAME: Any
DEFAULT_EXTENSIONS: Any
DEFAULT_IGNORE: Any
PROJECT_CONFIG_FILENAME: Any
apply_block_comment_rule: Any
apply_line_comment_rule: Any
execute_check_path_action: Any
load_config_files: Any
process_check_path_logic: Any
scan_for_files: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    'COMMENT_RULES',
    'COMMENT_RULES_BY_EXT',
    'CONFIG_FILENAME',
    'CONFIG_SECTION_NAME',
    'DEFAULT_EXTENSIONS',
    'DEFAULT_IGNORE',
    'PROJECT_CONFIG_FILENAME',
    'apply_block_comment_rule',
    'apply_line_comment_rule',
    'execute_check_path_action',
    'load_config_files',
    'process_check_path_logic',
    'scan_for_files'
]