# Path: modules/check_path/check_path_internal/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for check_path_internal"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

analyze_single_file_for_path_comment: Any
apply_block_comment_rule: Any
apply_line_comment_rule: Any
load_config_files: Any
merge_check_path_configs: Any
process_check_path_task_dir: Any
process_check_path_task_file: Any
scan_files: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    "analyze_single_file_for_path_comment",
    "apply_block_comment_rule",
    "apply_line_comment_rule",
    "load_config_files",
    "merge_check_path_configs",
    "process_check_path_task_dir",
    "process_check_path_task_file",
    "scan_files",
]