# Path: modules/zsh_wrapper/__init__.pyi (Auto-generated by pyi_generator.py)
"""Statically declared API for zsh_wrapper"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

DEFAULT_MODE: Any
DEFAULT_VENV: Any
DEFAULT_WRAPPER_ABSOLUTE_PATH: Any
DEFAULT_WRAPPER_RELATIVE_DIR: Any
execute_zsh_wrapper_action: Any
process_zsh_wrapper_logic: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = ['DEFAULT_MODE', 'DEFAULT_VENV', 'DEFAULT_WRAPPER_ABSOLUTE_PATH', 'DEFAULT_WRAPPER_RELATIVE_DIR', 'execute_zsh_wrapper_action', 'process_zsh_wrapper_logic']