# Path: utils/cli/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for cli"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

launch_editor: Any
prompt_config_overwrite: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = ['launch_editor', 'prompt_config_overwrite']