# Path: modules/pack_code/pack_code_internal/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for pack_code_internal"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

assemble_packed_content: Any
generate_tree_string: Any
resolve_filters: Any
resolve_output_path: Any
resolve_start_and_scan_paths: Any
scan_files: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    'assemble_packed_content',
    'generate_tree_string',
    'resolve_filters',
    'resolve_output_path',
    'resolve_start_and_scan_paths',
    'scan_files'
]