# Path: utils/cli/config_init/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for config_init"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

generate_config_content: Any
resolve_effective_defaults: Any
write_local_config: Any
write_project_config_section: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    "generate_config_content",
    "resolve_effective_defaults",
    "write_local_config",
    "write_project_config_section",
]