# Path: modules/stubgen/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for stubgen"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

AST_ALL_LIST_NAME: Any
AST_MODULE_LIST_NAME: Any
CONFIG_FILENAME: Any
CONFIG_SECTION_NAME: Any
DEFAULT_IGNORE: Any
DEFAULT_INCLUDE: Any
DYNAMIC_IMPORT_INDICATORS: Any
PROJECT_CONFIG_FILENAME: Any
classify_and_report_stub_changes: Any
execute_stubgen_action: Any
process_stubgen_logic: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    "AST_ALL_LIST_NAME",
    "AST_MODULE_LIST_NAME",
    "CONFIG_FILENAME",
    "CONFIG_SECTION_NAME",
    "DEFAULT_IGNORE",
    "DEFAULT_INCLUDE",
    "DYNAMIC_IMPORT_INDICATORS",
    "PROJECT_CONFIG_FILENAME",
    "classify_and_report_stub_changes",
    "execute_stubgen_action",
    "process_stubgen_logic",
]