# Path: stubgen/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for stubgen"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

AST_ALL_LIST_NAME: Any
AST_MODULE_LIST_NAME: Any
CONFIG_FILENAME: Any
CONFIG_SECTION_NAME: Any
DEFAULT_IGNORE: Any
DEFAULT_INCLUDE: Any
DYNAMIC_IMPORT_INDICATORS: Any
PROJECT_CONFIG_FILENAME: Any
classify_and_report_stub_changes: Any
collect_all_exported_symbols: Any
execute_stubgen_action: Any
extract_module_list: Any
find_gateway_files: Any
format_stub_content: Any
load_config_files: Any
merge_stubgen_configs: Any
process_stubgen_logic: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    'AST_ALL_LIST_NAME',
    'AST_MODULE_LIST_NAME',
    'CONFIG_FILENAME',
    'CONFIG_SECTION_NAME',
    'DEFAULT_IGNORE',
    'DEFAULT_INCLUDE',
    'DYNAMIC_IMPORT_INDICATORS',
    'PROJECT_CONFIG_FILENAME',
    'classify_and_report_stub_changes',
    'collect_all_exported_symbols',
    'execute_stubgen_action',
    'extract_module_list',
    'find_gateway_files',
    'format_stub_content',
    'load_config_files',
    'merge_stubgen_configs',
    'process_stubgen_logic'
]