# Path: modules/stubgen/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for stubgen"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

AST_ALL_LIST_NAME: Any
AST_MODULE_LIST_NAME: Any
DEFAULT_IGNORE: Any
DYNAMIC_IMPORT_INDICATORS: Any
SCAN_ROOTS: Any
execute_stubgen_action: Any
find_gateway_files: Any
process_stubgen_logic: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = ['AST_ALL_LIST_NAME', 'AST_MODULE_LIST_NAME', 'DEFAULT_IGNORE', 'DYNAMIC_IMPORT_INDICATORS', 'SCAN_ROOTS', 'execute_stubgen_action', 'find_gateway_files', 'process_stubgen_logic']