# Path: modules/stubgen/stubgen.spec.toml
#
# BẢN THIẾT KẾ TOOL CHO "sgen" (Stub Generator)
#

# --- 1. THÔNG TIN CƠ BẢN ---
[meta]
tool_name = "sgen"
script_file = "stubgen.py"
logger_name = "SGen"

# --- 2. CẤU HÌNH CLI (TYPER) ---
[cli.help]
description = "Tự động tạo file stub .pyi cho các module gateway động."
epilog = "Ví dụ: sgen . -f -R modules/auth,utils/core" 
allow_interspersed_args = true

# --- 3. DANH SÁCH ARGUMENTS (TYPER) ---

# Argument 1: target_dir (Path, Default: .)
[[cli.args]]
name = "target_dir"
type = "Path" 
default = "."
help = "Đường dẫn thư mục để bắt đầu quét (thư mục gốc). Mặc định là thư mục hiện tại (.)."
is_argument = true 

# Option 1: force (-f, --force)
[[cli.args]]
name = "force"
short = "-f"
type = "bool"
default = false
help = "Ghi đè file .pyi nếu đã tồn tại (không hỏi xác nhận)."

# Option 2: ignore (-I, --ignore)
[[cli.args]]
name = "ignore"
short = "-I"
type = "str"
help = "Danh sách pattern (fnmatch) ngăn cách bởi dấu phẩy để bỏ qua." 

# Option 3: restrict (-R, --restrict) - Mới
[[cli.args]]
name = "restrict"
short = "-R"
type = "str"
help = "Danh sách thư mục con (so với target_dir) ngăn cách bởi dấu phẩy để giới hạn quét." 

# --- 4. TÀI LIỆU ---
[docs]
enabled = true
short_description = "Một tiện ích để tạo file stub .pyi cho các module gateway Python động."