# Path: modules/stubgen/stubgen.spec.toml
#
# BẢN THIẾT KẾ TOOL CHO "sgen" (Stub Generator)
#

# --- 1. THÔNG TIN CƠ BẢN ---
[meta]
# Tên file thực thi trong /bin/
tool_name = "sgen"

# Tên file entrypoint Python trong /scripts/
script_file = "stubgen.py"

# Tên Logger
logger_name = "SGen"

# --- 2. CẤU HÌNH CLI (TYPER) ---
[cli.help]
description = "Automatically generates .pyi stub files for dynamic module gateways."
epilog = "Ví dụ: sgen /path/to/scan -f" 
allow_interspersed_args = true

# --- 3. DANH SÁCH ARGUMENTS (TYPER) ---

# Argument 1: target_dir (Path, Default: .)
[[cli.args]]
name = "target_dir"
type = "Path" 
default = "."
help = "Đường dẫn thư mục để bắt đầu quét. Mặc định là thư mục hiện tại (.)."
is_argument = true 

# Option 1: force (-f, --force)
[[cli.args]]
name = "force"
short = "-f"
type = "bool"
default = false
help = "Ghi đè file .pyi nếu đã tồn tại (không hỏi xác nhận)."

# --- 4. TÀI LIỆU ---
[docs]
enabled = true
short_description = "A utility to generate .pyi stub files for dynamic Python module gateways."