# Path: modules/path_checker/__init__.pyi (Auto-generated by pyi_generator.py)
"""Statically declared API for path_checker"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

COMMENT_RULES: Any
COMMENT_RULES_BY_EXT: Any
DEFAULT_EXTENSIONS_STRING: Any
DEFAULT_IGNORE: Any
apply_block_comment_rule: Any
apply_line_comment_rule: Any
handle_results: Any
process_path_updates: Any
scan_for_files: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = ['COMMENT_RULES', 'COMMENT_RULES_BY_EXT', 'DEFAULT_EXTENSIONS_STRING', 'DEFAULT_IGNORE', 'apply_block_comment_rule', 'apply_line_comment_rule', 'handle_results', 'process_path_updates', 'scan_for_files']