# Path: utils/core/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for core"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

Logger: Any
find_git_root: Any
format_value_to_toml: Any
get_submodule_paths: Any
is_git_repository: Any
is_path_matched: Any
load_config_template: Any
load_project_config_section: Any
load_toml_file: Any
merge_config_sections: Any
parse_comma_list: Any
parse_gitignore: Any
run_command: Any
write_toml_file: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = ['Logger', 'find_git_root', 'format_value_to_toml', 'get_submodule_paths', 'is_git_repository', 'is_path_matched', 'load_config_template', 'load_project_config_section', 'load_toml_file', 'merge_config_sections', 'parse_comma_list', 'parse_gitignore', 'run_command', 'write_toml_file']