# Path: utils/core/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for core"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

Logger: Any
compile_spec_from_patterns: Any
find_git_root: Any
format_value_to_toml: Any
get_submodule_paths: Any
git_add_and_commit: Any
is_git_repository: Any
is_path_matched: Any
load_and_merge_configs: Any
load_project_config_section: Any
load_text_template: Any
load_toml_file: Any
merge_config_sections: Any
parse_cli_set_operators: Any
parse_comma_list: Any
parse_gitignore: Any
resolve_config_list: Any
resolve_config_value: Any
resolve_set_modification: Any
run_command: Any
write_toml_file: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    'Logger',
    'compile_spec_from_patterns',
    'find_git_root',
    'format_value_to_toml',
    'get_submodule_paths',
    'git_add_and_commit',
    'is_git_repository',
    'is_path_matched',
    'load_and_merge_configs',
    'load_project_config_section',
    'load_text_template',
    'load_toml_file',
    'merge_config_sections',
    'parse_cli_set_operators',
    'parse_comma_list',
    'parse_gitignore',
    'resolve_config_list',
    'resolve_config_value',
    'resolve_set_modification',
    'run_command',
    'write_toml_file'
]