# Path: modules/format_code/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for format_code"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

DEFAULT_START_PATH: Any
execute_format_code_action: Any
process_format_code_logic: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    'DEFAULT_START_PATH',
    'execute_format_code_action',
    'process_format_code_logic'
]