# Path: modules/forc/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for format_code"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

CONFIG_FILENAME: Any
CONFIG_SECTION_NAME: Any
DEFAULT_EXTENSIONS: Any
DEFAULT_IGNORE: Any
DEFAULT_START_PATH: Any
PROJECT_CONFIG_FILENAME: Any
execute_format_code_action: Any
print_dry_run_report_for_group: Any
process_format_code_logic: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    "CONFIG_FILENAME",
    "CONFIG_SECTION_NAME",
    "DEFAULT_EXTENSIONS",
    "DEFAULT_IGNORE",
    "DEFAULT_START_PATH",
    "PROJECT_CONFIG_FILENAME",
    "execute_format_code_action",
    "print_dry_run_report_for_group",
    "process_format_code_logic",
]