# Path: modules/no_doc/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for no_doc"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

CONFIG_FILENAME: Any
CONFIG_SECTION_NAME: Any
DEFAULT_EXTENSIONS_MAP: Any
DEFAULT_IGNORE: Any
DEFAULT_START_PATH: Any
PROJECT_CONFIG_FILENAME: Any
analyze_file_content: Any
execute_ndoc_action: Any
load_config_files: Any
merge_ndoc_configs: Any
process_no_doc_logic: Any
scan_files: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    'CONFIG_FILENAME',
    'CONFIG_SECTION_NAME',
    'DEFAULT_EXTENSIONS_MAP',
    'DEFAULT_IGNORE',
    'DEFAULT_START_PATH',
    'PROJECT_CONFIG_FILENAME',
    'analyze_file_content',
    'execute_ndoc_action',
    'load_config_files',
    'merge_ndoc_configs',
    'process_no_doc_logic',
    'scan_files'
]