# Path: modules/stubgen/stubgen_internal/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for stubgen_internal"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

collect_all_exported_symbols: Any
extract_module_list: Any
find_gateway_files: Any
format_stub_content: Any
load_config_files: Any
merge_stubgen_configs: Any
process_single_gateway: Any
process_stubgen_task_dir: Any
process_stubgen_task_file: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = [
    'collect_all_exported_symbols',
    'extract_module_list',
    'find_gateway_files',
    'format_stub_content',
    'load_config_files',
    'merge_stubgen_configs',
    'process_single_gateway',
    'process_stubgen_task_dir',
    'process_stubgen_task_file'
]