# Path: modules/bootstrap/bootstrap_builder/__init__.pyi (Auto-generated by sgen)
"""Statically declared API for bootstrap_builder"""

from typing import Any, List, Optional, Set, Dict, Union
from pathlib import Path

build_argparse_arguments: Any
build_args_pass_to_core: Any
build_config_all_list: Any
build_config_constants: Any
build_config_imports: Any
build_path_expands: Any
build_typer_app_code: Any
build_typer_args_pass_to_core: Any
build_typer_main_signature: Any
build_typer_path_expands: Any

# Static declaration of exported symbols (for Pylance)
__all__: List[str] = ['build_argparse_arguments', 'build_args_pass_to_core', 'build_config_all_list', 'build_config_constants', 'build_config_imports', 'build_path_expands', 'build_typer_app_code', 'build_typer_args_pass_to_core', 'build_typer_main_signature', 'build_typer_path_expands']